# Generated by Django 4.0.3 on 2022-10-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=35, verbose_name='nombre')),
                ('edad', models.IntegerField(max_length=3, verbose_name='edad')),
                ('correo', models.EmailField(max_length=35, verbose_name='correo')),
                ('ciudad', models.TextField(verbose_name='ciudad')),
                ('direccion', models.TextField(verbose_name='direccion')),
            ],
        ),
    ]
